### ISSUE TITLE
Spring Boot BOM support

### ISSUE THREAD

**Issue by jasoet** [rife2/bld-spring-boot#4]
Can we add Support for Spring Boot BOM?
So we can define dependencies without specifying the version, and the version will be inferred from Spring Boot BOM. 

Can anyone give a pointer, I think I can implement this and send Pull Request.

**Comment by ethauvin** [comment]
I'm pretty sure that kind of BOM support would need to be added to bld itself, not just the via the extension. 

@gbevin Is that right?

**Comment by jasoet** [comment]
I agree, the BOM support should be added to bld. 

I am willing to help to implement this, It should be straightforward, but I will need some guidance.
I am currently working on creating an extension for this BOM support, not only for Spring Boot BOM but BOM in general.

While working on the Extension, I see there are a lot of functionalities that are already available on the bld itself, such as resolving dependencies, downloading artifacts, etc.

**Comment by ethauvin** [comment]
I believe there is some support for BOM in bld currently, but I'm not quite sure to the extent. 

@gbevin Can you shade some light?

**Comment by gbevin** [comment]
I think there's some implicit support for BOM reading support, not for generating, since a BOM is simply a sub-set of a POM. Integrating it into `bld` is probably the best approach. All that code is located in https://github.com/rife2/bld/tree/main/src/main/java/rife/bld/dependencies where `Xml2MavenPom.java` is likely the most interesting.

**Comment by jasoet** [comment]
Thanks, let me take a look at the bld code. 
Will close this issue and will send PR so we can continue the discussion.
